repos:
  - repo: local
    hooks:
      - id: mix-format
        name: mix format
        description: Run Elixir code formatter
        entry: mix format
        language: system
        files: \.(ex|exs)$
        pass_filenames: false

      - id: mix-compile
        name: mix compile
        description: Check if Elixir code compiles cleanly
        entry: mix compile --warnings-as-errors
        language: system
        files: \.(ex|exs)$
        pass_filenames: false</content>
