name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir: ['1.15', '1.16']
        otp: ['22', '23', '24', '25']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit

    - name: Run pre-commit checks
      run: pre-commit run --all-files

    - name: Check formatting
      run: mix format --check-formatted

    - name: Compile with warnings
      run: mix compile --warnings-as-errors

    - name: Run tests
      run: mix test --cover
